### ISSUE TITLE
Change the JS API to call different backends

### ISSUE THREAD

**Issue by wires** [typedefs/typedefs#104]

**Comment by epost** [comment]
The idea is that [ParserJS.idr](https://github.com/typedefs/typedefs/blob/98bf628abb94cc703d566ece2310c2e659a0fcda/parser.js/ParserJS.idr) call the various [Backend](https://github.com/typedefs/typedefs/tree/98bf628abb94cc703d566ece2310c2e659a0fcda/src/Backend)s instead of just the Haskell one.

**Comment by epost** [comment]
Duplicate of #49
