### ISSUE TITLE
Update to latest TParsec dependency

### ISSUE THREAD

**Issue by fredrikNordvallForsberg** [typedefs/typedefs#105]
I updated my installation of TParsec, where @clayrat's [additions](https://github.com/gallais/idris-tparsec/commit/6fafcaa894def6f2af86bc799e507013b56e7741) have been merged in. As a result, I get `Overlapping implementation` warnings which it would be nice to avoid (also more code that someone else maintains!). I guess updating should be done in two steps:

- [x] Update Nix-pkgs to point to the later commit (otherwise the travis build will break)
- [ ] Delete a bunch of code in `src/Parse.idr`

I'm very capable of carrying out the second step, but would appreciate it if someone who actually uses Nix could do the first...

**Comment by wires** [comment]
We can modify https://github.com/typedefs/typedefs/blob/master/.tparsec.nix and then get this into nix proper

**Comment by tg-x** [comment]
submitted nixpkgs PR

**Comment by fredrikNordvallForsberg** [comment]
Thanks! I pushed a hopefully-fix to the build failure in the nix-cleanup branch, which removes the code which is now upstream.
