### ISSUE TITLE
Nix 2.x build problems

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#11]
# Problem

The project will not build under Nix 2.x and Idris 1.2.0 using the build file [default.nix](https://github.com/typedefs/typedefs/blob/8/unit-tests/default.nix). (NB: this is a branch.) Like Alex points out, this problem is described under NixOS/nixpkgs#33994.

The error:
```
Entering directory `./src'
 Can't find import Builtins
 Can't find import Prelude
 Can't find import Data/Fin
```

# Reproduce

1) Run `nix-shell` in the project dir containing [default.nix](https://github.com/typedefs/typedefs/blob/8/unit-tests/default.nix).

2) From inside the shell, run:
   ```
   idris --build typedefs.ipkg
   ```

**Comment by clayrat** [comment]
Related to https://github.com/NixOS/nixpkgs/issues/33994

**Comment by epost** [comment]
Some WIP research notes: given the following lines in our derivation in `default.nix`, and using the `idris-1.2.0-with-packages` Nix package:

    stdenv.mkDerivation rec {
      ...
      idrisDeps = [ idrisPackages.prelude idrisPackages.base idrisPackages.contrib 
                    idrisPackages.builtins idris ];

      iwp = idrisPackages.with-packages idrisDeps;
      ...
    }
We should be able to invoke `idris` with the required libraries. First, in `nix-shell`, we set the desired library path:

    export "IDRIS_LIBRARY_PATH=${iwp}/libs"
    echo  $IDRIS_LIBRARY_PATH

Now if we compare `$IDRIS_LIBRARY_PATH` to the libdir, we see that `idris` hasn't picked it up:

    [nix-shell:~/dev/typedefs]$ echo $IDRIS_LIBRARY_PATH
    /nix/store/ihv6sjbc4pf6r019sgpb28p70vjsf46m-idris-1.2.0-with-packages/libs
    
    [nix-shell:~/dev/typedefs]$ idris --libdir
    /nix/store/1kgp81b5jib4q1zvpaa2hl3bq4xc2a8s-idris-1.2.0-with-packages/libs/

Alex verified on his Windows Nix installation, with Idris 1.3.0, the path *is* picked up.

The `$IDRIS_LIBRARY_PATH` we set contains the required libs, including `contrib`:

    [nix-shell:~/dev/typedefs]$ ls -l $IDRIS_LIBRARY_PATH
    total 0
    lrwxr-xr-x  1 root wheel  74 Jan  1  1970 00base-idx.ibc -> /nix/store/ysqbivpygmiaa6gdp9rpylshc4hbniy8-base-1.2.0/libs/00base-idx.ibc
    lrwxr-xr-x  1 root wheel  80 Jan  1  1970 00contrib-idx.ibc -> /nix/store/iqfgnn9qks46zs0k26d9wm0l2gwklk86-contrib-1.2.0/libs/00contrib-idx.ibc
    lrwxr-xr-x  1 root wheel  80 Jan  1  1970 00prelude-idx.ibc -> /nix/store/zz921z26h7gff4y9rxq13xfvkwk2nlsc-prelude-1.2.0/libs/00prelude-idx.ibc
    dr-xr-xr-x 10 root wheel 320 Jan  1  1970 base
    dr-xr-xr-x 14 root wheel 448 Jan  1  1970 contrib
    dr-xr-xr-x  9 root wheel 288 Jan  1  1970 prelude

...but the actual `libdir` does not contain the required libraries:

    [nix-shell:~/dev/typedefs]$ ls -l `idris --libdir`
    total 0
    lrwxr-xr-x  1 root wheel  74 Jan  1  1970 00base-idx.ibc -> /nix/store/ysqbivpygmiaa6gdp9rpylshc4hbniy8-base-1.2.0/libs/00base-idx.ibc
    lrwxr-xr-x  1 root wheel  80 Jan  1  1970 00prelude-idx.ibc -> /nix/store/zz921z26h7gff4y9rxq13xfvkwk2nlsc-prelude-1.2.0/libs/00prelude-idx.ibc
    dr-xr-xr-x 10 root wheel 320 Jan  1  1970 base
    dr-xr-xr-x  9 root wheel 288 Jan  1  1970 prelude

A workaround has been to do the symlinking manually:

```bash
# take the lib path we want from the Nix shell env var ${iwp}
export "IDRIS_LIBRARY_PATH=${iwp}/libs"
echo $IDRIS_LIBRARY_PATH
idris --libdir
# this doesn't contain the libs we want (in my case, esp. contrib)
ls -l `idris --libdir`

# keep the wrong lib path somewhere so we could restore it later
export "WRONG_IDRIS_LIBRARY_PATH=`idris --libdir`"
echo $WRONG_IDRIS_LIBRARY_PATH

export "idris_orig_lib_path_parent=$(dirname "$WRONG_IDRIS_LIBRARY_PATH")"
sudo mv $idris_orig_lib_path_parent/libs $idris_orig_lib_path_parent/libs-orig
sudo ln -s ${iwp}/libs $idris_orig_lib_path_parent/libs

# now the contrib library ought to be there
ls -l `idris --libdir`
```

Specifying individual libs on the `idris` command line using `-i` also seems to be ignored.

**Comment by TealG** [comment]
see #20
