### ISSUE TITLE
Create type provider

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#12]

**Comment by clayrat** [comment]
Another nice example: https://github.com/ctford/flying-spaghetti-monster

**Comment by clayrat** [comment]
One thing we should keep in mind is that type providers only work for the C backend.

**Comment by clayrat** [comment]
Apparently it's not as easy as I claimed - I'm hitting https://github.com/idris-lang/Idris-dev/issues/1807 now. Seems like it doesn't like the `Text` lexer/parser.

**Comment by clayrat** [comment]
One workaround for this would be trying out https://github.com/gallais/idris-tparsec/ as the parsing engine, which seemingly doesn't involve laziness.

**Comment by epost** [comment]
@clayrat I'm more than willing to consider other parser libs. Not sure if there are others worth investigating, but parsec-like libs sound good to me. feel free to make a separate issue out of that.

**Comment by clayrat** [comment]
Yep, the provider on top of `TParsec` seems to work fine.
