### ISSUE TITLE
JSON AST backend

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#129]
## Version 0: dictionary of named unparsed terms

 I would like another function in the JS API (or through other means, maybe XML or sth), a dictionary of `TypeName -> TypedefStr` for use in Studio:
  ```json
  { "Person": "(* String Date)"
  , "Date":   "(* Int Int Int)"
  , "Int":    "whatever"
  }
  ```

## Version 1: dictionary of named *parsed* terms

The next iteration would be a version of this dictionary but with some annotated AST instead of an unparsed String as values. With that, we can prettyprint, highlight and manipulate typedefs, e.g. on try.typedefs and in the Studio:

<dl>
  <dt>Person</dt>
  <dd>String * <span class="tdef-ref">Date</span></dd>
  <dt>Date</dt>
  <dd>Int * Int * Int</dd>
  <dt>Time</dt>
  <dd>Int * Int</dd>
</dl>

**Comment by wires** [comment]
what about running this on the input string? https://github.com/fwg/s-expression/blob/master/index.js
