### ISSUE TITLE
Codec for type definitions (Ty <-> Bits)

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#13]
Moved into this issue from an older source code comment by @wires:

- [ ] define binary schema
- [ ] `serialise : Ty -> Bits`
- [ ] `deserialise : Bits -> Ty`
- [ ]
    ```
    prf Ty codec :
      forall t:Ty. (serialise . deserialise) t == t
    ```
Related snippet:
```idris
showTy x =
  case x of
    Ty0 => "0"
    Ty1 => "1"
    (a .+. b) => showOp "+" a b
    (a .*. b) => showOp "*" a b
  where
    parens : String -> String
    parens s = "(" ++ s ++ ")"
    showOp : String -> Ty -> Ty -> String
    showOp op x y = parens $ (showTy x) ++ " " ++ op ++ " " ++ (showTy y)
```

**Comment by fredrikNordvallForsberg** [comment]
- [X] define binary schema
- [X] `serialise : Ty -> Bits`
- [X] `deserialise : Bits -> Ty`
- [ ]
    ```
    prf Ty codec :
      forall t:Ty. (serialise . deserialise) t == t
    ```

This is `serializeBinary` and `deserializeBinary` from [TermWrite](https://github.com/typedefs/typedefs/blob/master/src/TermWrite.idr) and [TermParse](https://github.com/typedefs/typedefs/blob/master/src/TermParse.idr) respectively.
