### ISSUE TITLE
Code is generated out of order and only for a single top-level typedef

### ISSUE THREAD

**Issue by andrevidela** [typedefs/typedefs#132]
From our experiments in [#645](https://github.com/statebox/pm/issues/645) we noticed that the generated code isn't generated in the same order as the source.

Moreover, only typedefs that are referenced by the last typedefs are generated. We should investigate if this is a behaviour that we want to keep and document or if it should be changed.

**Comment by clayrat** [comment]
The cause for the order issue is that defs are generated depth-first and then reversed, i.e. an AST of the form
```
     A
    / \
  B    E
 / \
C   D
```
will be serialized as
"E D C B A", even if C is a more basic type defined first.
