### ISSUE TITLE
Document the serialized format

### ISSUE THREAD

**Issue by andrevidela** [typedefs/typedefs#136]
The binary format in which terms are serialized and deserialized is not documented anywhere. This makes writing new backends way harder than it needs to be since we would need to copy the Haskell implementation instead of reading a document in prose.

The format should be documented with specification and tests

**Comment by clayrat** [comment]
From discussion in #128:

> For sums the first byte is which summand the following bytes represent (e.g. for `TSum [a, b, c]`, `i = 0` decodes a TDef `a`, `i = 1` a TDef `b` etc).
