### ISSUE TITLE
elba build missing dependencies

### ISSUE THREAD

**Issue by marcosh** [typedefs/typedefs#138]
It looks like `elba.toml` is missing some dependencies (e.g. `ziman/idris-bytes`)

**Comment by andrevidela** [comment]
So I've looked into it and I tried to add an `elba.toml` file to the `idris-bytes` projects but it doesn't seem to work out of the box. I've opened an issue on the elba project here https://github.com/elba/elba/issues/54

**Comment by marcosh** [comment]
nice, let's see (if and) what they'll answer

**Comment by andylokandy** [comment]
@andrevidela I think this issue is resolved by https://github.com/elba/elba/commit/4501ea6eb76b1ad2111262b1e5885eb78ffd8dcb and the `include` issue https://github.com/elba/elba/issues/56 is just an improvment and is not necessary here.

**Comment by andrevidela** [comment]
@andylokandy You are right it works now! It think we can close this thanks to you.

**Comment by andrevidela** [comment]
MIght have talked too early, something else is wrong

**Comment by andylokandy** [comment]
What is going wrong?

**Comment by andrevidela** [comment]
@andylokandy nothing to do with elba (afaik) just configuration issues
