### ISSUE TITLE
Improve the ergonomics of the command line

### ISSUE THREAD

**Issue by andrevidela** [typedefs/typedefs#139]
Currently the `typedef_parser` build only takes a string as input and output on stdout.

The issue with that is that there is no way to extract the output as a haskell file other than copy-paste from the output. There is no way to define a source and a destination file either and there is no way to get documentation from there.

So we should:

1. implement `--help`
2. implement --source typedef.tdef --dest types.hs --backend haskell

**Comment by clayrat** [comment]
Can we close this?

**Comment by andrevidela** [comment]
yep, I assumed it closed automatically, didn't notice it was still open
