### ISSUE TITLE
Codec for terms of type (Ty <-> Bits)

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#14]
Moved into this issue from an older source code comment by @wires:
- [ ] discuss binary schema [in upcoming meeting](https://hackmd.io/OsZVarQHRoKPJNIZfpKYuA?edit)
- [x] `serialise : (t:Ty) -> x:(tau t) -> Bits`
- [x] `deserialise : Bits -> (t:Ty ** tau t)`
- [ ]
  ```
    prf Term codec :
      forall t:Ty. forall (x:tau t). (deserialise . serialise) t x == t
  ```

**Comment by wires** [comment]
Decided in dev meeting that actual binary format for now is not so important, will stick with some easy to parse string

**Comment by clayrat** [comment]
Started work in https://github.com/typedefs/typedefs/tree/term-codec branch
