### ISSUE TITLE
Split the API between generateType and generateDef

### ISSUE THREAD

**Issue by andrevidela** [typedefs/typedefs#143]
Currently `generateDef` sometimes return the term serializers and deserializers (for Haskell for example) or the data type definition (in other backends). There should probably be two functions for those two functionalities.

This could also allow to add new options to generate types and serializers, typically we could generate all datatype signatures in a file and serializers in another. Or only generate serializers without datatypes because they use existing types.

This would be a good opportunity to split the haskell backend into two parts, one for types and one for terms.

**Comment by clayrat** [comment]
We already sort of have it, with `ASTGen` having two separate methods: `generateTyDefs` and `generateTermDefs`, it's just that the latter returns empty output for everything except Haskell. We only glue everything back together in [generateDefs](https://github.com/typedefs/typedefs/blob/master/src/Typedefs/Backend.idr#L65). I think the main part missing for this is the ability to generate multiple files and imports within them?

**Comment by clayrat** [comment]
@andrevidela Also which branch should I ideally use a base, I'm guessing [fix-ref-parsing](https://github.com/typedefs/typedefs/tree/fix-ref-parsing)?

**Comment by andrevidela** [comment]
yes [fix-ref-parsing](https://github.com/typedefs/typedefs/tree/fix-ref-parsing),

and yes we already "sort of have it" but it's really not intuitive. If you look at the JS main file you can see how degenerate the API is. We use `generate`, `generateDefs` but `generateDefs` doesn't generate termdefs for ReasonML, only for haskell.

Ideally we would use `generateDefs` for haskell and `generateTyDefs` for the two others.

Also we need to split up the _Type_ generation for Haskell and the _term_ generation. They're both in the same file and it's a huge mess.

**Comment by andrevidela** [comment]
So after the cleaning up here is what we probably need

```idris
interface GenTypes typeAST where
    genTypes : TopLevelDef -> Either CompilerError typeAST

interface GenTerms termAST where
    genTerms : TopLevelDef -> Either CompilerError termAST

interface GenUtils termAST where
    genUtils : TopLevelDef -> termAST

interface RenderSource languageAST where
    render : languageAST -> Doc

renderFile : (GenTypes ast, GenTerms ast, GenUtils ast, RenderSource ast) 
          => TopLevelDef -> Either CompilerError Doc
```

I guess we can salvage `CodegenIndep` to replace `GenUtils` and `renderFile`
