### ISSUE TITLE
Revisit the current naming of modules and organisation

### ISSUE THREAD

**Issue by andrevidela** [typedefs/typedefs#145]
During my trial with newbies I have discovered two things:

- When installing typedefs the name `typedefs-parser` isn't intuitively understood by users.
- The origanisation of folders isn't straight forward either, typically the _binary_ `typedefs` is in the path `/parser` whereas the library is in `/src`

The user-facing binary should be called `typedefs` so that calling it looks like this:

```
typedefs -i "(+ 1 1)" --stdout
```

The current `typedefs` should be then renamed `typedefs-core` not to conflict and make a distinction between what is _user facing_ and what is _backend logic_. I think the word "core" encapsulate clearly that this is what drives typedefs

## Proposed solution

- rename `typedefs` into `typedefs-core`
- rename `typdefs-parser` into `typedefs` 
- rename `typedefs-parser-js` into `typedefs-js`
- rename the folder `parser` into `typedefs`
- rename the folder `parser.js` into `typedefs-js`
- rename the folder `src` into `typedefs-core`

Those changes require changing the binary names in `.ipkg`, `elba.toml` and `.nix` files as well.

What do you think?

**Comment by epost** [comment]
I think this is a huge improvement. 👍 I mentioned a variant on the above:
- `typedefs` -> `typedefs`
- `typedefs-parser` -> `typedefs-cli`

But I'll gladly add my blessing to the three thumbs up that this one has. That should save us a lot of time at the dev meeting. :P

**Comment by andrevidela** [comment]
Actually it's not as straight forward as I hoped since ipkg files can't have `sourcedir` pointing to a folder with dashes. We can either shelf this until it does (I think I have a fix for it) or we can rename stuff to `typedefs.core` and `typedefs.js`

**Comment by epost** [comment]
Well, that still seems like an improvement. Perhaps we could use underscores instead of dashes?

**Comment by clayrat** [comment]
What about splitting `parser/cli` and `js` into separate repos?

**Comment by clayrat** [comment]
Also, should we get rid of `examples`?

**Comment by andrevidela** [comment]
@clayrat I guess it depends what we're trying to achieve. It would certainly make the build system easier to maintain since `typedefs-core` would become an external dependency. But it would have two disadvantages that are too great to be considered viable in my opinion:

- It would decouple `typedefs-core` and the cli which would hide errors due to API changes and would make every new feature require two PR, one for a new version of the core and one for cli.
- We would need to have people download and use the `cli` but most errors, bug reports and PR will have to be on `typedefs-core`, which is doable but isn't necessarily straight foward to understand when using the program.

I don't have an opinion on examples yet. Maybe they should be in the Statebox Docs.
