### ISSUE TITLE
Update Nix tag/release for tparsec

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#146]
PR #142 is blocked because the build fails on an now out-of-date tparsec dependency.

Alex:
> yeah this needs a newer nix tag/release for tparsec
> it's not hard but requires someone with a working nix installation to generate a hash
> then we could push the update to nixpkgs

**Comment by clayrat** [comment]
https://github.com/NixOS/nixpkgs/pull/63623

**Comment by clayrat** [comment]
Above is merged, closing
