### ISSUE TITLE
Help Martin in figuring out of TD can be useful for Ethereum 2

### ISSUE THREAD

**Issue by wires** [typedefs/typedefs#168]
Martin and me spoke a bit about the applicability of typedefs to Ethereum 2.0 ABI, I'm opening this issue to remind us of this.

ref.
- [RLP](https://github.com/ethereum/wiki/wiki/%5BEnglish%5D-RLP)
- [ABI](https://solidity.readthedocs.io/en/develop/abi-spec.html

- [ ] setup call with Martin?

cc @MrChico

**Comment by FabrizioRomanoGenovese** [comment]
I reached out. Let's wait!

**Comment by wires** [comment]
related https://github.com/ethereum/EIPs/issues/1882 @emideluxe
