### ISSUE TITLE
Make unit test actually check stuff instead of just printing

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#17]
We may want to keep it simple for now and write a few custom test functions, or we may want to look into one of these:

- https://github.com/jfdm/idris-testing
- https://github.com/pheymann/specdris

Other suggestions welcomed.

**Comment by tg-x** [comment]
Done in d485ecefb03538e55e16a8bf15a55bb035896cd5

There are two different parsers -- `Parse` and `TParse` -- are both in use and should both be tested?
For now I added both, though the second test suite is only run if the first passes.
