### ISSUE TITLE
 [Question] How does this compare to ADL?

### ISSUE THREAD

**Issue by sideeffffect** [typedefs/typedefs#192]
Sorry if this is a wrong channel for such questions, but I would be interested how would you compare Typedefs with ADL :smile:

https://github.com/timbod7/adl

(reverse question: https://github.com/timbod7/adl/issues/76 )

**Comment by andrevidela** [comment]
ADL is another Interface Description Language and it compares similarly to Thrift or Protobuf (albeit with a lot more features that are relevant to Typedefs).

Typedefs emerged from Statebox's need to define generic data in different context (web API, wiring diagrams, categories).

Mostly the biggest difference is the fundamental calculus that backs typedefs: an F-algebra (that you can find entirely defined there https://github.com/typedefs/typedefs/blob/master/src/Typedefs/Typedefs.idr#L15) which is traversed and compiled into different interpretations of the same algebraic expression.

This allows Typedefs to benefits from properties likes defining a discrete category with functions as morphisms (as defined here, though the PR is stale https://github.com/typedefs/typedefs/pull/116 )

This has the benefit of being extremely generic while staying relatively simple (the algebra fits on an A4 page). The flipside is that it doesn't benefit from standard constructs like Int64, Strings, Arrays and such. They need to all be reconstructed from the basic building blocks. 

There is  PR in the works to implement _specialised_ types which will depend on the backend and/or runtime representation of them.

**Comment by timbod7** [comment]
Interesting project! I've been working on [ADL][1] for some years now and it's nice to see another project working toward similar goals. A couple of responses to the above:

> ADL is another Interface Description Language and it compares similarly to Thrift or Protobuf 

I don't consider ADL to be an Interface Definition Language, but rather a data modelling language. We do use it to define interfaces, but also to define sql db schemas, UI forms etc. Much of our application logic gets expressed in terms of ADL defined types. 

> (typdefs...) has the benefit of being extremely generic while staying relatively simple (the algebra fits on an A4 page).

ADL's [meta model][2] is admitted more complex (196 lines), though still not too unweildy.

> There is PR in the works to implement specialised types

It sounds like this is somewhat equivalent to ADL's custom type mappings, as a means
of extending the language core with per-backend custom definitions.


[1]:https://github.com/timbod7/adl
[2]:https://github.com/timbod7/adl/blob/master/adl/stdlib/sys/adlast.adl

**Comment by andrevidela** [comment]
I'm closing this, but feel free to reopen if you have more questions, we might put them in the readme later.
