### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by wires** [typedefs/typedefs#2]
Issue to collect related projects and write a Hashi-corp like "Typedefs v.s. $project"

List:

- Universal Binary Format http://ubf.github.io/ubf/ubf-user-guide.en.html

**Comment by clayrat** [comment]
Verified de/serialization lib, a part of the http://distributedcomponents.net/ project:

https://github.com/uwplse/cheerios
(turns out I misremembered the name)

**Comment by clayrat** [comment]
https://kaitai.io/

**Comment by clayrat** [comment]
http://www.staff.science.uu.nl/~swier004/publications/2017-tyde-a.pdf Geest, Swierstra, "Generic Packet Descriptions: Verified Parsing and Pretty Printing of Low-Level Data"

**Comment by clayrat** [comment]
https://github.com/dloss/binary-parsing a nice compendium

**Comment by epost** [comment]
Moved to https://hackmd.io/22MJzoZFRBycNiDgN1nKKg, which is linked from this repo's README.md
