### ISSUE TITLE
Try out idris-tparsec

### ISSUE THREAD

**Issue by clayrat** [typedefs/typedefs#21]
Try switching the parsing library from `Text.Parser` to https://github.com/gallais/idris-tparsec/ to circumvent the laziness issues in https://github.com/typedefs/typedefs/issues/12

Paper: https://gallais.github.io/pdf/agdarsec18.pdf
Examples: https://github.com/gallais/idris-tparsec/tree/master/src/Examples

**Comment by clayrat** [comment]
A high-level comparison to `Text.Parser` is given by the author here https://www.reddit.com/r/Idris/comments/7erqd7/tparsec_total_parser_combinators_in_idris/:
```
in Text.Parser you define a (coinductive) grammar for your language and parsing is done by munching down the grammar by induction over the size of the input string.
In TParsec you have what is basically Haskell's Parser a = String -> [(String, a)] but with fancier types. You combine these parsers directly by using the combinators you're used to but they have been assigned fancier types which prevents you from writing problematic parsers (e.g. the typical non-terminating left-recursive parsers).
```

Some of the known issues with `Text.Parser` are described in https://github.com/idris-lang/Idris-dev/pull/4286, https://github.com/idris-lang/Idris-dev/issues/4421, https://github.com/idris-lang/Idris-dev/issues/4271

+ less setup, more vanilla FP-style parsing, i.e., no separate definition of token maps, lexers, grammars etc
+ no laziness anywhere, so we're not affected by https://github.com/idris-lang/Idris-dev/issues/1807 when using it in a type provider
+ likely to have less issues with proving termination, see above

- probably is not great performance wise, but also see above
- error reporting is currently nonexistant, see https://github.com/gallais/idris-tparsec/issues/6

**Comment by epost** [comment]
@clayrat Thanks, nice overview! Let's go with TParsec; the issues with that seem like the most fixable ones, and it's nice.
