### ISSUE TITLE
error : cannot generate JSON schema for open typedefs

### ISSUE THREAD

**Issue by banacorn** [typedefs/typedefs#210]
I was fiddling with https://try.typedefs.com, and tried the "Maybe" example

```
(name Maybe (+ 1 (var 0)))
```

The Haskell and the ReasonML backend is doing fine, but it's having trouble generating JSON Schema. The "Generated Code" output becomes blank.

I'm not sure what went wrong, and I have no idea what "open typedefs" means, but this is here's what the website outputs to the console:

```
main.js:113 generated = <error : cannot generate JSON schema for open typedefs>
main.js:85 setResult: text = <error : cannot generate JSON schema for open typedefs>
```

**Comment by andrevidela** [comment]
This is expected, JSON and javascript don't have type parameters so we do not generate a definition for them. Maybe we should document this better.

This is a known limitation that we aren't looking to lift, so I will close that in the meantime. Don't hesitate to reopen if you find something related to this :)

**Comment by banacorn** [comment]
Thank you, I see!
