### ISSUE TITLE
Serialization of terms constructed out of nested Mu's crashes

### ISSUE THREAD

**Issue by clayrat** [typedefs/typedefs#211]
E.g., `serialize [] [] (TList `ap` [TNat]) (fromList {tdef=TNat} $ map fromNat [3])`

**Comment by clayrat** [comment]
Seem like deserialization is also bugged:

```
> :exec deserialize [] [] (TList `ap` [TNat]) "(inn (right (both (inn (right (inn (right (inn (left ())))))) (inn (left ())))))"
Nothing
```

**Comment by andrevidela** [comment]
This is a blocker for stbx-core

**Comment by clayrat** [comment]
This only seems to happen when the inner Mu is "big", i.e., it works for lists of form `[0,1,1,0,1..]`, but breaks down when the numbers get bigger than 1.

**Comment by clayrat** [comment]
This seems to be a deep problem arising from the fact that we shift all variables at application, so the inner Mu's self-referencing var shifts to point at the outer Mu.
