### ISSUE TITLE
Add ergonomic functions to convert from and to typical typedefs

### ISSUE THREAD

**Issue by andrevidela** [typedefs/typedefs#212]
We found while working on stbx-core that interacting with Idris would be much easier if we had access to some generic utility function to convert from and to Typedefs. Here are some functions that would be nice to have and expose:

```idris
toNat : Ty [] TNat -> Nat
toList : Ty [def] TList -> List def
toList' : Ty [] (TList `ap`[ tdef]) -> List (Ty [] tdef)
fromNat : Nat -> Ty [] TNat
fromList : List a -> Ty [a] TList
fromList' : List (Ty [] tdef) -> Ty [] (TList `ap` tdef)
toMaybe : Ty [a] TMaybe -> Maybe a
toMaybe' : Ty [] (TMaybe `ap` [tdef]) -> Maybe (Ty [] tdef)
-- etc..
```

Maybe we should have this as an interface?

**Comment by clayrat** [comment]
I guess we've added most of this in #216? Conversions for `Maybe` and `Either` are missing however so we might track those here.

**Comment by andrevidela** [comment]
Actually this is entirely superseeded by #225 isn't it? since `Ty' StandardIdris [] TNat = Nat` and so on for `Either`, `List`, `Nat` and `Maybe`.
