### ISSUE TITLE
Fix Type Application for references in Idris Type Interpretation

### ISSUE THREAD

**Issue by andrevidela** [typedefs/typedefs#220]
This doesnt work

```idris
test : GammaTy [(1** List)] ((RRef 0) `ap` TProd [TVar 0, TVar 0]) Nat
test = [(1,2)]
```

Indeed `(RRef 0) `ap` TProd [TVar 0, TVar 0]` is executed to be `TProd [TVar0, TVar0]` because `ap` simply replaces `RRef 0` by its argument.

-------------

To expand on that more here is the use case:

We want to use _specialised_ versions of `Nat` and `List` so that we do not have to deal with their `Mu` notation in their term representation. For this, we simply represent `Nat` as being `TNat` which are references to the index 0, likewise for `List`.

```
TNat : TDef 2
TNat = Ref 1

TList : TDef 2
TList = Ref 0
```

We now want to have a pair of lists of nats for this we use the existing constructor `TProd` to construct our pair

```
ListOfPairs : TDef 2
ListOfPairs = TList `ap` TProd [TNat,  TNat]
```

However this definition won't work because `TList` is of type `TDefR 2` and therefore requires 2 arguments to be applied, we're only giving it one. But moreover, this use of `ap` is completely wrong, since it will simply replace the reference `RRef 0` by `TNat` which is not what we expect. 

This is due to how variables and references behave when they are used as type constructors and are applied to something else. You can't apply them to anything because they will themselves be substituted by the values given in argument, but that is not what we mean. What we mean is that they need to say as variables, until they are instanciated as a type constructor in their target language

```
PairOfLists : Ty [List, Nat] (TList `ap` TProd [TNat, TNat])
PairOfLists = [(1,4), (2,5), (3,6)]
```

---------------

This use case appears in fsm-oracle where executions are defined like so: 
```
TNat : TDefR 3
TNat = RRef 0

TListPair : TDefR 3
TListPair = RRef 1

TListNat : TDefR 3
TListNat = RRef 2

TPetriExec = TProd [TProd [TNat , TListPair], TListNat,  TTree]

FromExec : Ty [Nat, List (List Nat, List Nat), List Nat] TPetriExec -> …
```

But ideally should be defined as

```
TPetriExec = TProd [TProd [TNat , TList `ap` TProd [TNat, TNat]], TList `ap` TNat,  TTree]
FromExec : Ty [Nat, List] TPetriExec -> …
```

**Comment by fredrikNordvallForsberg** [comment]
Like you say, obviously the definition of `ap (RRef i)` is wrong -- resolved references are not type variables. My gut feeling is that there would be more chances of getting it right if `RRef`s and `TVar`s weren't counted by the same index, ie if `TDef` was indexed by two numbers.

Apart from that, if you want to instantiate `RRef`s with type constructors, not just types, you should probably keep track of the arity/type of the `RRef`, and represent an `RRef` together with a spine of arguments. In particular, `ap` would just add to this list.

Does this make sense? Otherwise I can try to make it a little bit more concrete sometime next week.

**Comment by andrevidela** [comment]
All of that make sense but I don't really see how to keep track of applications. Do you mean something like

```
data TDef : (vars : Fin n) -> (refs : Fin m) -> Type where
    Ref : Fin (S m) -> List (k **  l ** TDef k l) -> TDef n (S m) 
````
?

@clayrat was mentioning moving to something closer to system-F, typically because this way we would get arity inference for variables that are applied. What do you think?

**Comment by fredrikNordvallForsberg** [comment]
If you allow type constructors, you are already past System F and at System Fω... Although thankfully, at least you have no plans to add impredicative universal quantification, I hope.

But, what this means concretely is that you need to keep track of kinds in the `TDef`s, and its not enough to record *how many* `Ref`s you have, but also their kinds. For instance:
```
TApp : TDef n gamma (K => J) -> TDef n gamma K -> TDef n gamma J
Ref : T \in gamma -> TDef n gamma T
```
(I tried fleshing out the neutral spine in `Ref` idea above, but it gets quite messy when taking kinds into account, so probably better not to, and consider a general `TApp` like that instead.)

This is obviously quite a big departure from current typedefs though, are you sure this is needed?

**Comment by andrevidela** [comment]
> This is obviously quite a big departure from current typedefs though, are you sure this is needed?

I'm sure this is needed in the sense that we want to be able to say "this reference is a type constructor" since we want to be able to import types like `List` `Maybe` etc.

However, from a business point of view this isn't strictly necessary since the Haskell backend just map lookup (Map String HsType) to find the correct Haskell type using the name of the reference. This will be mostly useful for using Typedefs from `Ty`. 

This personally makes me think of programming with "holes", would this be a possibly interesting conference paper?
