### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#27]
- [x] compile the typedefs compiler to Javascript
- [x] do so in a separate... Nix build file? or perhaps something a bit more workable
- [x] create an HTML page with a textarea and a `compile` button, and invoke the JS typedefs compiler on the textarea content
- [x] discuss further nicifications

**Comment by tg-x** [comment]
added a `typedefs-parser-js` package, build it with
`nix-build -A typedefs-parser-js`

the idris code is in `ParserJS.idr` that generates JS code that runs on load and calls a JS function to get the source and another JS function to set the result

then open the resulting `share/typedefs/js/typedefs-parser.html`

**Comment by epost** [comment]
@tg-x here is the ACE editor thing that Emil built: https://github.com/statebox/aql-ide. I think this issue is done and any further UI work should go in a separate issue.
