### ISSUE TITLE
JS API should expose top-level methods

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#49]
## Outline

The idea is that [ParserJS.idr](https://github.com/typedefs/typedefs/blob/98bf628abb94cc703d566ece2310c2e659a0fcda/parser.js/ParserJS.idr) call the various [Backend](https://github.com/typedefs/typedefs/tree/98bf628abb94cc703d566ece2310c2e659a0fcda/src/Backend)s instead of just the Haskell one.

- [x] expose Haskell backend
- [x] expose ReasonML backend
- [x] expose JSON backend
- [x] expose type parser
- [x] remove `main` function
- [x] add a `String` switch to select the desired backend

## Older version of this issue (plz update!)

This is a probably somewhat outdated TODO:

- [ ] expose `showTDef`
- [ ] ~~expose `Backend.Haskell`: `generate`, `generateType`~~
- [ ] ~~expose `TermCodec` (`serialize` and `serializeMu`?)~~

Re invocation of the Haskell backend, @clayrat writes

> It's generally `generate <typedef>` or `generateType <typedef>`
> depends on whether you're making type synonyms or actual new data
> I'll try to add those tests later today

See https://github.com/typedefs/typedefs/issues/48.

Alex also mentioned https://github.com/idris-lang/Idris-dev/pull/4073, which should allow us to create interfaces for Node (and, after some browserification, hopefully also for the browser).

**Comment by andrevidela** [comment]
copy API from Haskell
