### ISSUE TITLE
Document, clarify, clean up and format the main ADT and examples.

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#5]
We want to capture some of the documentation and learnings in source code comments, and generally present things as clearly as possible.

- [x] add doc comments to main types
- [x] add doc comments to examples
- [x] make sure the order of examples makes sense
- [x] update makefile with an additional `doc` target
- [x] move Jelle's todo list from the bottom of `Typedefs.idr` into issues or something

**Comment by wires** [comment]
Great suggestion; remarks:

- I'm a big fan of literate code, we could turn the main .idr file into a literate idris file and turn it into a human readable article
- I sketched out some typedefs stuff [here](https://hackmd.io/22MJzoZFRBycNiDgN1nKKg?both), please have a look and feel add comments

**Comment by epost** [comment]
- Yeah, I've been doing that; commit upcoming, this issue was just so I could attach it.
- Cool! I'll have a look. Your README update from a while back was hugely helpful too.
