### ISSUE TITLE
JS compilation via Nix fails when including Backend.Haskell in ParserJS.idr

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#58]
Idris's JS compiler doesn't seem to like
```
import Typedef
import Parse
import Backend.Haskell
```
It complains about:
```
[nix-shell:/app/typedefs]# idris --build typedefs-parser-js.ipkg
Entering directory `./parser.js'
Type checking ./ParserJS.idr
Uncaught error: Elaborating {__infer_0} arg {ival_0}: NoSuchVariable run__IO
FAILURE: "idris-codegen-javascript" ["./ParserJS.ibc","-o","/app/typedefs/typedefs_parser.js"]
Leaving directory `./parser.js'
```
Removing the `import Backend.Haskell` makes the error go away and compilation succeed.

*Update:* this was using Nix 2.1.3 on macOS (pre-Mojave)

**Comment by clayrat** [comment]
This seems to me like an issue with the nix pipeline - everything seems to compile manually here.

**Comment by wires** [comment]
I noticed it's possible to build nix stuff using travis https://docs.travis-ci.com/user/languages/nix/ does it make sense to try to set that up?

**Comment by epost** [comment]
@wires we already do that :9

**Comment by tg-x** [comment]
`nix-build -A typedefs-parser-js`

```
Entering directory `./parser.js'
Type checking ./ParserJS.idr
ParserJS.idr:12:8-86:
   |
12 | main = setResult $ parseThenStrFun !getSource (\td => Haskell.generate $ DPair.snd td)
   |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
When checking right hand side of main with expected type
        JS_IO ()

When checking an application of function Parse.parseThenStrFun:
        No such variable Haskell.generate
```

**Comment by tg-x** [comment]
this was due to an unclean source tree possibly containing an old version of the typedefs lib,
and was fixed by:
`make clean`
