### ISSUE TITLE
Let-bindings

### ISSUE THREAD

**Issue by epost** [typedefs/typedefs#61]
We should probably introduce some aliasing/let binding syntax, so that we can define them in parts and referred back to, like in the `ListNat` test.

Syntax suggestions? Shall we introduce list literals (which i don't particularly like, but wth):
```
(let [ (name Maybe (+ 1 (var 0))
     , (mu ...)
     , ...
     ]
     (....tdef...)
)
```
Does this make any sense? :P I'm half-tempted to break sexp syntax where and go for a list of definitions like

```
foo = (+ 1 1)
bar = (...)
```

Actually, how should this interact with naming through `TName` and `TMu`?

**Comment by clayrat** [comment]
I think we should reuse the `TName`/`TMu` mechanism, the idea would be basically to just parse a list of  tdefs where the latter could refer to the names in the former, probably just the toplevel ones. Maybe no extra syntax is even needed, just some kind of sequencing notation e.g. semicolons.
