### ISSUE TITLE
Application?

### ISSUE THREAD

**Issue by clayrat** [typedefs/typedefs#79]
We probably want some internal notion of application if we want to be able to generate something like the following:
```
data List a = Nil | Cons a (List a)
data Nat = Z | S Nat
type ListNat = List Nat
```
One way would be to look at http://assert-false.net/arnaud/papers/A%20dissection%20of%20L.pdf, and have some degenerate form of it, e.g., where we only keep the contexts and never do actual substitution. This could also help with https://github.com/typedefs/typedefs/issues/61

**Comment by kjekac** [comment]
System L is extremely interesting and that paper is extremely well-written, very easy get caught in it and "accidentally" read a bit more than strictly necessary – thanks for the reference!

However I fail to see which extra tools System L provides us with? I mean, an inference system with a monotonically growing context would probably be useful to keep track of names, but other that? Is there anything specific in the computational model itself that you see a connection to?

**Comment by clayrat** [comment]
There was some talk on supporting codata in the future :) However this will probably make code generation a lot more complicated.

**Comment by kjekac** [comment]
I also worked out my idea from yesterday in some greater detail. I think that the following is approaching what we are after:

```idris
mutual
  data TBody : (n : Nat) -> Type where
    T0    :                                          TBody n
    T1    :                                          TBody n
    TSum  :                Vect (2 + k) (TBody n) -> TBody n
    TProd :                Vect (2 + k) (TBody n) -> TBody n
    TVar  :                (i:Fin (S n))          -> TBody (S n)
    TApp  : TBody (S n) -> TBody k                -> TBody (n + (k `minus` n))
    TWrap :                TDef n                 -> TBody n
  
  data TDef : (n : Nat) -> Type where
    TMu   : Name -> Vect k (Name, TBody (S n)) -> TDef n
    TName : Name -> TBody n                    -> TDef n
```

This allows us to construct a bunch of different data types, the following all typecheck:
 
```idris
nat : TDef 0
nat = TMu "Nat" [("Z", T1), ("S", TVar 0)]

list : TDef 1
list = TMu "List" [("Nil", T1), ("Cons", TProd [TVar 1, TVar 0])]

natList : TBody 0
natList = TWrap list `TApp` TWrap nat

maybe : TDef 1
maybe = TName "Maybe" $ TSum [T1, TVar 0]

maybeNat : TBody 0
maybeNat = TWrap maybe `TApp` TWrap nat

maybeNatList : TBody 0
maybeNatList = TWrap list `TApp` maybeNat

natPlusVar : TBody 1
natPlusVar = TSum [TWrap (weakenTDef nat 1 LTEZero), TVar 0]
-- `weakenTDef` of course needs to be defined for our new data types,
-- this is trivial except for the `TApp` case which is a total mess.
-- Nevertheless, the above typechecks and evaluates without encountering holes.

either : TDef 2
either = TMu "Either" [("Left", TVar 1), ("Right", TVar 2)]

eitherNatVar : TBody 1
eitherNatVar = (TWrap either
                `TApp` TWrap nat)
                `TApp` TVar 0 
```

However, the following example fails:

```idris
bit : TDef 0
bit = TWrap maybe `TApp` the (TBody 0) T1

   |
91 | bit = TWrap maybe `TApp` the (TBody 0) T1
   |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
When checking right hand side of bit with expected type
        TDef 0

Type mismatch between
        TBody (n + minus k n) (Type of TApp _ _)
and
        TDef 0 (Expected type)

Specifically:
        Type mismatch between
                TBody (plus n (minus k n))
        and
                TDef 0
```

I haven't been able to figure out why this is. As far as I can see, the typing should be exactly the same as in `maybeNat`.

But maybe even more importantly, as mentioned in the comments it is a nightmare to implement `weakenTBody` for the `TApp` case, if it is even possible. So I am increasingly skeptical of this approach (it also feels very hacky and unprincipled...), but maybe someone can spot a relatively easy way to make it workable, that I'm missing?

**Comment by clayrat** [comment]
> `TApp  : TBody (S n) -> TBody k                -> TBody (n + (k minus n))`

 This is what McBride calls "green slime" - functions in data indices tend to mess up dependent patmat. A very quick fix is to move this inside the constructor, i.e.:

 `TApp  : TBody (S n) -> TBody k -> m = n + (k minus n) -> TBody m`

**Comment by clayrat** [comment]
@fredrikNordvallForsberg says:

>  I think life would be easier without `TApp`, or there will be redundant representations, e.g. `TApp (Var 0) [td]` vs `td`
> For the motivating `List Nat` example, one can simply perform the substitution manually: 
> ```
> TName "ListNat" $ 
>  TMu "List"
>    [ ("Nil", T1)
>    , ("Cons", TProd [(TMu "Nat" [("Z", T1), ("S", TVar 0)]) , TVar 0])
>    ]
>```
> It's true that this doesn't extend to nested types, or other higher-order fixed points, but hopefully there is no need for that -- it'll probably be hard enough to implement typedefs in a non-Haskelly language as it is...

**Comment by kjekac** [comment]
Consensus against; subsumed be #61.
